version: "3.4"
services:
  nethermind-xdai.dnp.dappnode.eth:
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: 1.13.4
    image: "nethermind-xdai.dnp.dappnode.eth:1.0.0"
    restart: unless-stopped
    security_opt:
      - "seccomp:unconfined"
    volumes:
      - "data:/data"
    environment:
      NETHERMIND_CONFIG: xdai
      NETHERMIND_SYNCCONFIG_FASTSYNC: "true"
      NETHERMIND_JSONRPCCONFIG_ENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_HOST: 0.0.0.0
      NETHERMIND_INITCONFIG_WEBSOCKETSENABLED: "true"
      NETHERMIND_NETWORKCONFIG_DISCOVERYPORT: 30404
      NETHERMIND_NETWORKCONFIG_P2PPORT: 30404
      EXTRA_OPTS: ""
    ports:
      - 30404:30404/tcp
      - 30404:30404/udp
volumes:
  data: {}
